version: '2'
services:
  api:
    build: ./api
    ports:
     - "8080:8080"
    depends_on:
     - redis
    volumes:
     - ./api:/app/api
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"